name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [
          18.x, # LTS as of 2023-11
          20.x  # current as of 2023-11
        ]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: npm install
      - run: npm run build
      - run: npm run test
      - run: npm run examples
