name: Test
on:
  push:
  pull_request:
  schedule:
    - cron: "43 19 * * *"
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.x # Maintenance LTS as of 2024-07
          - 20.x # Active LTS as of 2024-07
          - 22.4.x # Current as of 2024-07, npm/cli#7657
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - run: npm run lint
      - run: npm run test
      - run: npm run examples:node
      - run: npm run examples:esbuild
  bun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
      - uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run build
      - run: bun run test:short
      - run: bun run examples:bun
